# Este workflow irá construir e publicar uma aplicação Java no Azure App Service.

name: Build and deploy JAR app to Azure Web App - smartroutine-api

on:
  push:
    branches:
      - master  # Acionado quando há um push para a branch 'master'
  workflow_dispatch: # Permite acionar manualmente a partir da aba "Actions"

jobs:
  build-and-deploy: # Renomeei o job para ser mais descritivo
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o seu código do repositório
      - uses: actions/checkout@v2

      # 2. Configura o ambiente Java na versão 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Entra na pasta do backend e compila o projeto, gerando o .jar
      - name: Build with Maven
        run: mvn clean package --file pom.xml
        working-directory: ./Codigo/backend

      # 4. PASSO CRUCIAL: Faz o login no Azure usando as credenciais secretas
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_342981571477435F8E24D99D4DC951F6 }} # A sua "chave" de publicação. NÃO a altere.

      # 5. Publica o ficheiro .jar gerado no Azure App Service
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'smartroutine-api' # O nome do seu App Service
          package: './Codigo/backend/target/*.jar' # O caminho CORRETO para o ficheiro .jar
